# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Bayram/Desktop/Proje_1.0/Ogretmen.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_Ogretmen(object):
    def setupUi(self, Form_Ogretmen):
        Form_Ogretmen.setObjectName("Form_Ogretmen")
        Form_Ogretmen.resize(500, 620)
        Form_Ogretmen.setMinimumSize(QtCore.QSize(500, 620))
        Form_Ogretmen.setMaximumSize(QtCore.QSize(500, 620))
        self.label = QtWidgets.QLabel(Form_Ogretmen)
        self.label.setGeometry(QtCore.QRect(70, 70, 200, 25))
        self.label.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form_Ogretmen)
        self.label_3.setGeometry(QtCore.QRect(70, 110, 200, 25))
        self.label_3.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form_Ogretmen)
        self.label_4.setGeometry(QtCore.QRect(70, 150, 200, 25))
        self.label_4.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form_Ogretmen)
        self.label_5.setGeometry(QtCore.QRect(70, 190, 200, 25))
        self.label_5.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form_Ogretmen)
        self.label_6.setGeometry(QtCore.QRect(70, 230, 200, 25))
        self.label_6.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(Form_Ogretmen)
        self.label_2.setGeometry(QtCore.QRect(70, 270, 200, 25))
        self.label_2.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(Form_Ogretmen)
        self.label_7.setGeometry(QtCore.QRect(70, 310, 200, 25))
        self.label_7.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form_Ogretmen)
        self.label_8.setGeometry(QtCore.QRect(70, 350, 200, 25))
        self.label_8.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.lineEdit_Adi = QtWidgets.QLineEdit(Form_Ogretmen)
        self.lineEdit_Adi.setGeometry(QtCore.QRect(280, 70, 131, 25))
        self.lineEdit_Adi.setObjectName("lineEdit_Adi")
        self.lineEdit_Soyadi = QtWidgets.QLineEdit(Form_Ogretmen)
        self.lineEdit_Soyadi.setGeometry(QtCore.QRect(280, 110, 131, 25))
        self.lineEdit_Soyadi.setObjectName("lineEdit_Soyadi")
        self.lineEdit_Kabul_Edilm_Gun = QtWidgets.QLineEdit(Form_Ogretmen)
        self.lineEdit_Kabul_Edilm_Gun.setGeometry(QtCore.QRect(280, 390, 131, 25))
        self.lineEdit_Kabul_Edilm_Gun.setObjectName("lineEdit_Kabul_Edilm_Gun")
        self.lineEdit_OgrNo = QtWidgets.QLineEdit(Form_Ogretmen)
        self.lineEdit_OgrNo.setGeometry(QtCore.QRect(280, 150, 131, 25))
        self.lineEdit_OgrNo.setObjectName("lineEdit_OgrNo")
        self.lineEdit_Tcno = QtWidgets.QLineEdit(Form_Ogretmen)
        self.lineEdit_Tcno.setGeometry(QtCore.QRect(280, 190, 131, 25))
        self.lineEdit_Tcno.setMaxLength(11)
        self.lineEdit_Tcno.setObjectName("lineEdit_Tcno")
        self.lineEdit_Kabul_Edl_Gun = QtWidgets.QLineEdit(Form_Ogretmen)
        self.lineEdit_Kabul_Edl_Gun.setGeometry(QtCore.QRect(280, 350, 131, 25))
        self.lineEdit_Kabul_Edl_Gun.setObjectName("lineEdit_Kabul_Edl_Gun")
        self.comboBox_Fakulte = QtWidgets.QComboBox(Form_Ogretmen)
        self.comboBox_Fakulte.setGeometry(QtCore.QRect(280, 230, 131, 25))
        self.comboBox_Fakulte.setObjectName("comboBox_Fakulte")
        self.comboBox_Bolum = QtWidgets.QComboBox(Form_Ogretmen)
        self.comboBox_Bolum.setGeometry(QtCore.QRect(280, 270, 131, 25))
        self.comboBox_Bolum.setObjectName("comboBox_Bolum")
        self.comboBox_StajTuru = QtWidgets.QComboBox(Form_Ogretmen)
        self.comboBox_StajTuru.setGeometry(QtCore.QRect(280, 310, 131, 25))
        self.comboBox_StajTuru.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox_StajTuru.setObjectName("comboBox_StajTuru")
        self.comboBox_StajTuru.addItem("")
        self.comboBox_StajTuru.addItem("")
        self.pushButton_Kaydet = QtWidgets.QPushButton(Form_Ogretmen)
        self.pushButton_Kaydet.setGeometry(QtCore.QRect(60, 450, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Kaydet.setFont(font)
        self.pushButton_Kaydet.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Kaydet.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_Kaydet.setObjectName("pushButton_Kaydet")
        self.label_10 = QtWidgets.QLabel(Form_Ogretmen)
        self.label_10.setGeometry(QtCore.QRect(70, 530, 171, 25))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.comboBox_Sorgu = QtWidgets.QComboBox(Form_Ogretmen)
        self.comboBox_Sorgu.setGeometry(QtCore.QRect(270, 530, 171, 22))
        self.comboBox_Sorgu.setObjectName("comboBox_Sorgu")
        self.pushButton_Duzenle = QtWidgets.QPushButton(Form_Ogretmen)
        self.pushButton_Duzenle.setGeometry(QtCore.QRect(360, 560, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Duzenle.setFont(font)
        self.pushButton_Duzenle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Duzenle.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_Duzenle.setObjectName("pushButton_Duzenle")
        self.label_11 = QtWidgets.QLabel(Form_Ogretmen)
        self.label_11.setGeometry(QtCore.QRect(60, 10, 401, 41))
        self.label_11.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form_Ogretmen)
        self.label_12.setGeometry(QtCore.QRect(70, 390, 200, 25))
        self.label_12.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.pushButton_Sil = QtWidgets.QPushButton(Form_Ogretmen)
        self.pushButton_Sil.setGeometry(QtCore.QRect(270, 560, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Sil.setFont(font)
        self.pushButton_Sil.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Sil.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_Sil.setObjectName("pushButton_Sil")
        self.label_Ogr_BosAlan = QtWidgets.QLabel(Form_Ogretmen)
        self.label_Ogr_BosAlan.setGeometry(QtCore.QRect(110, 510, 311, 20))
        self.label_Ogr_BosAlan.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_Ogr_BosAlan.setObjectName("label_Ogr_BosAlan")
        self.label_EklemeBasarili = QtWidgets.QLabel(Form_Ogretmen)
        self.label_EklemeBasarili.setGeometry(QtCore.QRect(150, 510, 311, 20))
        self.label_EklemeBasarili.setStyleSheet("color: rgb(0, 170, 0);")
        self.label_EklemeBasarili.setObjectName("label_EklemeBasarili")
        self.label_SilmeBasarili = QtWidgets.QLabel(Form_Ogretmen)
        self.label_SilmeBasarili.setGeometry(QtCore.QRect(240, 590, 311, 20))
        self.label_SilmeBasarili.setStyleSheet("color: rgb(0, 170, 0);")
        self.label_SilmeBasarili.setObjectName("label_SilmeBasarili")
        self.label_Ogr_NoBos = QtWidgets.QLabel(Form_Ogretmen)
        self.label_Ogr_NoBos.setGeometry(QtCore.QRect(200, 590, 311, 20))
        self.label_Ogr_NoBos.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_Ogr_NoBos.setObjectName("label_Ogr_NoBos")
        self.label_FakulteSecin = QtWidgets.QLabel(Form_Ogretmen)
        self.label_FakulteSecin.setGeometry(QtCore.QRect(420, 230, 81, 21))
        self.label_FakulteSecin.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_FakulteSecin.setObjectName("label_FakulteSecin")
        self.label_Kayitli = QtWidgets.QLabel(Form_Ogretmen)
        self.label_Kayitli.setGeometry(QtCore.QRect(240, 500, 201, 20))
        self.label_Kayitli.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_Kayitli.setObjectName("label_Kayitli")

        self.retranslateUi(Form_Ogretmen)
        QtCore.QMetaObject.connectSlotsByName(Form_Ogretmen)

    def retranslateUi(self, Form_Ogretmen):
        _translate = QtCore.QCoreApplication.translate
        Form_Ogretmen.setWindowTitle(_translate("Form_Ogretmen", "Form"))
        self.label.setText(_translate("Form_Ogretmen", "Adı : "))
        self.label_3.setText(_translate("Form_Ogretmen", "Soyadı : "))
        self.label_4.setText(_translate("Form_Ogretmen", "Öğrenci No : "))
        self.label_5.setText(_translate("Form_Ogretmen", "Tc No : "))
        self.label_6.setText(_translate("Form_Ogretmen", "Fakülte : "))
        self.label_2.setText(_translate("Form_Ogretmen", "Bölüm : "))
        self.label_7.setText(_translate("Form_Ogretmen", "Staj Türü : "))
        self.label_8.setText(_translate("Form_Ogretmen", "Kabul Edilen Gün Sayısı : "))
        self.comboBox_StajTuru.setCurrentText(_translate("Form_Ogretmen", "Zorunlu"))
        self.comboBox_StajTuru.setItemText(0, _translate("Form_Ogretmen", "Zorunlu"))
        self.comboBox_StajTuru.setItemText(1, _translate("Form_Ogretmen", "İsteğe Bağlı"))
        self.pushButton_Kaydet.setText(_translate("Form_Ogretmen", "Kaydet"))
        self.label_10.setText(_translate("Form_Ogretmen", "Öğrenci No ile Sorgula : "))
        self.pushButton_Duzenle.setText(_translate("Form_Ogretmen", "Düzenle"))
        self.label_11.setText(_translate("Form_Ogretmen", " Öğrenci Düzenleme  -  Ekleme  -  Silme Paneli"))
        self.label_12.setText(_translate("Form_Ogretmen", "Kabul Edilmeyen Gün Sayısı : "))
        self.pushButton_Sil.setText(_translate("Form_Ogretmen", "Sil"))
        self.label_Ogr_BosAlan.setText(_translate("Form_Ogretmen", "Ekleme yapılamadı. Lütfen boş bir alan bırakmayınız!"))
        self.label_EklemeBasarili.setText(_translate("Form_Ogretmen", "Öğrenci Başarıyla Eklendi ✓"))
        self.label_SilmeBasarili.setText(_translate("Form_Ogretmen", "Öğrenci Başarıyla Silindi ✓"))
        self.label_Ogr_NoBos.setText(_translate("Form_Ogretmen", "Öğrenci Silinemedi, Lütfen Öğrenci No Giriniz !"))
        self.label_FakulteSecin.setText(_translate("Form_Ogretmen", "Fakulte Secin !"))
        self.label_Kayitli.setText(_translate("Form_Ogretmen", "Bu öğrenci zaten sistemde kayıtlıdır !"))

