# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Bayram/Desktop/Proje_1.0/Tasarım.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(550, 400))
        Form.setMaximumSize(QtCore.QSize(550, 400))
        font = QtGui.QFont()
        font.setPointSize(6)
        Form.setFont(font)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(217, 217, 217);\n"
"")
        self.label_Ogretmen = QtWidgets.QLabel(Form)
        self.label_Ogretmen.setGeometry(QtCore.QRect(30, 90, 250, 60))
        self.label_Ogretmen.setMaximumSize(QtCore.QSize(250, 60))
        self.label_Ogretmen.setStyleSheet("font: 75 24pt \"MS Shell Dlg 2\";\n"
"color: #ffffff;\n"
"background-color: #fe0202;")
        self.label_Ogretmen.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_Ogretmen.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_Ogretmen.setObjectName("label_Ogretmen")
        self.label_Yonetici = QtWidgets.QLabel(Form)
        self.label_Yonetici.setGeometry(QtCore.QRect(30, 20, 250, 60))
        self.label_Yonetici.setMaximumSize(QtCore.QSize(9999, 9999))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_Yonetici.setFont(font)
        self.label_Yonetici.setStyleSheet("font: 75 24pt \"MS Shell Dlg 2\";\n"
"color: #ffffff;\n"
"background-color: rgb(0, 170, 127);")
        self.label_Yonetici.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_Yonetici.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_Yonetici.setWordWrap(False)
        self.label_Yonetici.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_Yonetici.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_Yonetici.setObjectName("label_Yonetici")
        self.label_Ogrenci = QtWidgets.QLabel(Form)
        self.label_Ogrenci.setGeometry(QtCore.QRect(30, 160, 250, 60))
        self.label_Ogrenci.setMaximumSize(QtCore.QSize(250, 60))
        self.label_Ogrenci.setStyleSheet("font: 75 24pt \"MS Shell Dlg 2\";\n"
"color: #ffffff;\n"
"background-color: #0055ff;")
        self.label_Ogrenci.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_Ogrenci.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_Ogrenci.setObjectName("label_Ogrenci")
        self.radioButton_Yonetici = QtWidgets.QRadioButton(Form)
        self.radioButton_Yonetici.setGeometry(QtCore.QRect(300, 50, 82, 17))
        self.radioButton_Yonetici.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_Yonetici.setText("")
        self.radioButton_Yonetici.setObjectName("radioButton_Yonetici")
        self.radioButton_Ogretmen = QtWidgets.QRadioButton(Form)
        self.radioButton_Ogretmen.setGeometry(QtCore.QRect(300, 120, 82, 17))
        self.radioButton_Ogretmen.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_Ogretmen.setText("")
        self.radioButton_Ogretmen.setObjectName("radioButton_Ogretmen")
        self.radioButton_Ogrenci = QtWidgets.QRadioButton(Form)
        self.radioButton_Ogrenci.setGeometry(QtCore.QRect(300, 180, 82, 17))
        self.radioButton_Ogrenci.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_Ogrenci.setText("")
        self.radioButton_Ogrenci.setObjectName("radioButton_Ogrenci")
        self.label_Id = QtWidgets.QLabel(Form)
        self.label_Id.setGeometry(QtCore.QRect(70, 260, 120, 35))
        self.label_Id.setStyleSheet("font: 75 italic 12pt \"MS Sans Serif\";background-color: rgb(241, 241, 241);")
        self.label_Id.setObjectName("label_Id")
        self.label_Sifre = QtWidgets.QLabel(Form)
        self.label_Sifre.setGeometry(QtCore.QRect(70, 300, 120, 35))
        self.label_Sifre.setStyleSheet("background-color: rgb(241, 241, 241);font: 75 italic 12pt \"MS Sans Serif\";")
        self.label_Sifre.setObjectName("label_Sifre")
        self.lineEdit_ID = QtWidgets.QLineEdit(Form)
        self.lineEdit_ID.setGeometry(QtCore.QRect(220, 260, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_ID.setFont(font)
        self.lineEdit_ID.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_ID.setObjectName("lineEdit_ID")
        self.lineEdit_Sifre = QtWidgets.QLineEdit(Form)
        self.lineEdit_Sifre.setGeometry(QtCore.QRect(220, 300, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_Sifre.setFont(font)
        self.lineEdit_Sifre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_Sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Sifre.setObjectName("lineEdit_Sifre")
        self.pushButton_Giris = QtWidgets.QPushButton(Form)
        self.pushButton_Giris.setGeometry(QtCore.QRect(250, 350, 91, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_Giris.setFont(font)
        self.pushButton_Giris.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"color: #ffffff;\n"
"background-color: #708090;")
        self.pushButton_Giris.setObjectName("pushButton_Giris")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(340, 50, 71, 55))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 24pt \"Papyrus\";\n"
"color: rgb(255, 170, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(420, 50, 101, 55))
        self.label_2.setStyleSheet("font: 24pt \"Papyrus\";\n"
"color: rgb(255, 170, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(330, 110, 171, 45))
        self.label_3.setStyleSheet("font: 24pt \"Papyrus\";\n"
"color: rgb(255, 170, 0);")
        self.label_3.setObjectName("label_3")
        self.label_hata = QtWidgets.QLabel(Form)
        self.label_hata.setGeometry(QtCore.QRect(210, 330, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_hata.setFont(font)
        self.label_hata.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_hata.setObjectName("label_hata")
        self.label_GirisTuru = QtWidgets.QLabel(Form)
        self.label_GirisTuru.setGeometry(QtCore.QRect(30, 220, 301, 31))
        self.label_GirisTuru.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 0);")
        self.label_GirisTuru.setObjectName("label_GirisTuru")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Staj Takip Sistemi"))
        self.label_Ogretmen.setText(_translate("Form", " Öğretmen Girişi"))
        self.label_Yonetici.setText(_translate("Form", "  Yönetici Girişi"))
        self.label_Ogrenci.setText(_translate("Form", "   Öğrenci Girişi"))
        self.label_Id.setText(_translate("Form", "Kullanıcı Adı :"))
        self.label_Sifre.setText(_translate("Form", "Şifre : "))
        self.pushButton_Giris.setText(_translate("Form", "Giriş"))
        self.label.setText(_translate("Form", "Staj"))
        self.label_2.setText(_translate("Form", "Takip"))
        self.label_3.setText(_translate("Form", "       Sistemi"))
        self.label_hata.setText(_translate("Form", "Girdiğiniz Id veya Şifre Hatalıdır !"))
        self.label_GirisTuru.setText(_translate("Form", "Lütfen Giriş Yapmadan önce Kullanıcı Tipini Seçiniz !"))

